env: "local"
storage_path: "postgres://postgres:postgres@localhost:5432/friends?sslmode=disable"
users_grpc_client:
  uri: "localhost:44044"
  timeout: 5s
  queue_size: 32
  num_workers: 4
grpc_srv:
  port: 44045
  timeout: 5s
graph_storage:
  uri: "neo4j://localhost:7687"
  username: "neo4j"
  password: "Test12345678"
  realm: ""