version: '3'

tasks:
  # gen:proto:
  #   dir: ./api/proto
  #   desc: Generate Go code from Protobuf files
  #   cmds:
  #     - mkdir -p users
  #     - protoc -I=. \
  #         --go_out=. --go_opt=paths=source_relative \
  #         --go-grpc_out=. --go-grpc_opt=paths=source_relative \
  #         users/user.proto

  gen:users-proto:
    dir: ./api
    desc: Generate Go code from Protobuf files for users servers
    cmds:
      - protoc -I proto proto/users/user.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative


  tidy:proto:
    dir: ./api/proto
    desc: Run go mod tidy in proto module
    cmds:
      - go mod tidy

  tidy:desktop:
    dir: ./desktop
    desc: Run go mod tidy in desktop app
    cmds:
      - go mod tidy

  tidy:users:
    dir: ./go/users
    desc: Run go mod tidy in users service
    cmds:
      - go mod tidy

  tidy:all:
    desc: Run go mod tidy for all modules
    deps: [tidy:proto, tidy:desktop, tidy:users]

  gen:all:
    desc: Generate all code and tidy modules
    deps: [gen:users-proto, tidy:all]

  exec:users:
    dir: ./go/users
    desc: Run user service
    cmds:
      - go run ./cmd/users
