services:
  postgres:
    image: postgres:16
    container_name: friends_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: friends
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: friends_neo4j
    environment:
      NEO4J_AUTH: neo4j/Test12345678
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt (driver)
    volumes:
      - neo4jdata:/data

volumes:
  pgdata:
  neo4jdata:
